version: '3'
services:
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ./dev/docker/nginx/templates:/etc/nginx/templates
      - .:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=playground.local
      - NGINX_PORT=80
    networks:
      custom_net:
        ipv4_address: 172.28.1.1
  php:
    build: ./dev/docker/phpfpm/.
    container_name: php-fpm
    volumes:
      - .:/usr/share/nginx/html
    networks:
      custom_net:
        ipv4_address: 172.28.1.2
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    networks:
      custom_net:
        ipv4_address: 172.28.1.3
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      custom_net:
        ipv4_address: 172.28.1.4
networks:
  custom_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
